# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-04-13 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('situacao_folha', models.CharField(blank=True, default='', max_length=1)),
                ('admissao', models.DateField()),
                ('demissao', models.DateField(blank=True, null=True)),
                ('vencto_exp', models.DateField(blank=True, null=True)),
                ('salario', models.FloatField()),
                ('funcao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=5)),
                ('protocolo', models.CharField(blank=True, default='', max_length=10)),
                ('funcao_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('E', 'Em andamento'), ('P', 'Pendente'), ('A', 'Adiado'), ('C', 'Concluído'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('valor', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('E', 'Extra')], default='N', max_length=1)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='colaboradores', to='project_manager.Colaborador')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor', to='project_manager.Colaborador')),
            ],
        ),
    ]
