# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-04-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicial',
            field=models.DateTimeField(),
        ),
    ]
